#1.项目启动的端口
#server.port=8080

#2.数据库连接参数
#spring.datasource.url=jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=12345678

#初始化连接大小
#spring.datasource.druid.initial-size=5
#最小连接数。
#spring.datasource.druid.min-idle=5
#最大连接数
#spring.datasource.druid.max-active=200
#超时时间
#spring.datasource.druid.max-wait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.datasource.druid.time-between-eviction-runs-millis= 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.datasource.druid.min-evictable-idle-time-millis=300000
#验证连接是否有效sql
#spring.datasource.druid.validation-query=SELECT 1 FROM DUAL
#空闲时检查
#spring.datasource.druid.test-while-idle=true
#获取连接时先验证连接是否有效
#spring.datasource.druid.test-on-borrow=true
#归还连接时先验证连接是否有效
#spring.datasource.druid.test-on-return=true
#打开  PSCache
#spring.datasource.druid.pool-prepared-statements=true
#指定每个连接上PSCache的大小
#spring.datasource.druid.max-pool-prepared-statement-per-connection-size=20


#logging.config=classpath=logback.xml

server:
  port:8080

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456

logging:
  level:
    com.example.springboot.dao: debug

  config: classpath:logback.xml


mybatis:
  type-aliases-package: com.example.springboot.pojo
  mapper-locations: classpath:/com/example/springboot/mapper/*.xml
#  global-config.logic-delete-value: 0
#  global-config.logic-not-delete-value: 1
#  global-config.sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
